---
trigger:
  branches:
    include:
      - main

resources:
  repositories:
    - repository: templates
      type: git
      name: ${project_or_organization_name}/${repository_name_templates}

parameters:
  - name: terraform_action
    displayName: Terraform Action to perform
    type: string
    default: 'apply'
    values:
      - 'apply'
      - 'destroy'
  - name: terraform_cli_version
    displayName: Terraform CLI Version
    type: string
    default: 'latest'

lockBehavior: sequential

extends:
  template: ${cd_template_path}@templates
  parameters:
    terraform_action: $${{ parameters.terraform_action }}
    root_module_folder_relative_path: ${root_module_folder_relative_path}
    terraform_cli_version: $${{ coalesce(parameters.terraform_cli_version, 'latest') }}
%{ if multi_region_enabled ~}
%{ for region in regions ~}
    variable_group_name_${region.key}: ${region.variable_group_name}
    environment_name_plan_${region.key}: ${region.environment_plan}
    environment_name_apply_${region.key}: ${region.environment_apply}
    service_connection_name_plan_${region.key}: ${region.service_connection_plan}
    service_connection_name_apply_${region.key}: ${region.service_connection_apply}
%{ endfor ~}
%{ else ~}
    variable_group_name: ${variable_group_name}
    environment_name_plan: ${environment_name_plan}
    environment_name_apply: ${environment_name_apply}
    service_connection_name_plan: ${service_connection_name_plan}
    service_connection_name_apply: ${service_connection_name_apply}
%{ endif ~}
